apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
        - name: member-service
          image: ${REPOSITORY_TAG}
          ports:
            - containerPort: 8050
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka/"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"


---
apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  selector:
    app: member-service
  ports:
    - name: http
      port: 8050
      targetPort: 8050
  type: ClusterIP

