#
#server:
#  port: 8050
#spring:
#  application:
#    name: member-service
#  config:
#    import: optional:configserver:http://localhost:8888
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://miyembromemberdev.ch2cua0wgb3v.eu-north-1.rds.amazonaws.com:5432/member
#    username: arjay
#    password: Miyembro24122022
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        format_sql: true
#        type: TRACE
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: "654581949282-dmvkqbivaa8rmvem7ipjbas30p5akkrm.apps.googleusercontent.com"
#            client-secret: "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"
#            scope: openid, profile, email
#            redirect-uri: "http://localhost:8222/login/oauth2/code/google"
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#    datatype:
#      jsr310:
#        serializer: com.fasterxml.jackson.datatype.jsr310.ser.LocalDateSerializer
#        deserializer: com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#keyStore:
#  path: keystore.jks
#  password: password
#
#application:
#  config:
#    organization-url: http://localhost:8222/api/v1/organizations
#
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    org.springframework.cloud.netflix.eureka.EurekaClient: DEBUG
#    com.netflix.discovery: DEBUG
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#aws:
#  s3:
#    access:
#      key: AKIAT4GVRMTPBTFGNH77
#    secret:
#      key: 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
#    region: eu-north-1
#    bucket: arjay-fileupload
#
#jwt:
#  secret: "TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V"
#  expiration: 3600000