spring:
  application:
    name: member-service
  config:
    import: optional:configserver:http://localhost:8888

application:
  config:
    organization-url: http://localhost:8222/api/v1/organizations